### ISSUE TITLE
'+1' is parsed as a string if caption is ''

### ISSUE THREAD

**Issue by Gaiiden** [kristerkari/iOSBadge#1]
Not sure if this is a bug or not, but I'm also not sure how else I should be doing this. I want to add +1 to the badge number each time I call

`$("#" + craftInfo[3]).iosbadge({ theme: 'red', size: 20, content: '+1',  position: 'top-left' });`

It's quite elegant and works fine when the object `craftInfo[3]` is pointing to is called more than one time, showing just a number equal to the amount of times it was called. However if the object is only called once via this statement, the badge shows "+1" instead of just "1".

If this is working as intended, then I'm not sure how I should be checking to see if the object badge caption has not already been set in order to set `caption: '1'` in that case. I've tried several ways to access the `caption` property through jQuery and haven't figured out how (not a lot of jQuery experience)

**Comment by kristerkari** [comment]
Fixed in https://github.com/kristerkari/iOSBadge/pull/3
